# Generated by Django 4.2.6 on 2023-10-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('nSerie', models.CharField(max_length=40)),
            ],
        ),
    ]
