# Generated by Django 4.2.1 on 2023-11-03 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('veiculos', '0001_initial'),
        ('motoristas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaManutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(choices=[('CA', 'Carregamento'), ('ES', 'Escavação'), ('GE', 'Geotécnia'), ('FE', 'Fila de Espera'), ('MT', 'Manutenção')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('data_inicio', models.DateField(null=True)),
                ('data_entrega', models.DateField(null=True)),
                ('hora_inicio', models.DateTimeField(null=True)),
                ('hora_fim', models.DateTimeField(null=True)),
                ('finalizado', models.BooleanField(default=False)),
                ('identificador', models.CharField(blank=True, max_length=24, null=True)),
                ('motorista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='motoristas.motorista')),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='veiculos.veiculo')),
            ],
        ),
    ]
