# Generated by Django 4.2.1 on 2023-11-03 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_rename_servico_servico_veiculo_servico_operacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='data_entrega',
        ),
        migrations.RemoveField(
            model_name='servico',
            name='data_inicio',
        ),
    ]
