# Generated by Django 4.2.1 on 2023-11-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_remove_servico_data_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='identificador',
            field=models.CharField(blank=True, max_length=52, null=True),
        ),
    ]
